name: "LoRaWAN Add-on"
description: "A complete LoRaWAN Network Server with Chirpstack"
version: "0.0.1"
slug: "lorawan"
image: "halorawan/{arch}-addon-lorawan"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ports:
  8080/tcp: 8080
devices: 
  - /dev/ttyACM0
udev: true